{% set name = "asv" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 141a7fa6e90d63e39db6314e6ea6b7c5b81dfd7556dd03723ff43ede9688965b

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  patches:
    - 0001-Only-install-asv-sources.patch

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools >=64
    - setuptools_scm >=6.2
    - wheel
  run:
    - python
    - asv_runner >=0.2.1
    - json5
    - virtualenv
    - tomli
    - tabulate
    - colorama  # [win]
    - pyyaml    # [python_impl != "pypy"]
    - pympler   # [python_impl != "pypy"]

test:
  imports:
    - asv
  requires:
    - pip
  commands:
    - pip check
    - python -m asv --help
    - asv --help

about:
  home: https://github.com/airspeed-velocity/asv
  license: BSD-3-Clause
  license_file: LICENSE.rst
  summary: A simple Python benchmarking tool with web-based reporting

  description: |
    It is primarily designed to benchmark a single project over its lifetime
    using a given suite of benchmarks. The results are displayed in an
    interactive web frontend that requires only a basic static webserver to
    host.
  doc_url: http://asv.readthedocs.io/en/latest/index.html
  dev_url: https://github.com/airspeed-velocity/asv

extra:
  recipe-maintainers:
    - CJ-Wright
    - saraedum
    - xhochy
    - mlondschien
    - mattip
    - jbrockmendel
    - datapythonista
    - HaoZeke
