{% set name = "asv" %}
{% set version = "0.2.1" %}
{% set sha256 = "f0bd3f75d20a3802139f11b8c7e7e82876d00470aef17a99acc10849414b7470" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - sphinx
    - sphinx_bootstrap_theme
    - six
  run:
    - python
    - six

test:
  imports:
    - asv
#  requires:
#    - pytest
#  files:
#    - {{ SRC_DIR }}/test/
#  commands:
#    - cd {{ SRC_DIR }}/test/
#    - py.test

about:
  home: https://github.com/spacetelescope/asv
  license: BSD-3
  license_file: LICENSE.rst
  summary: 'A simple Python benchmarking tool with web-based reporting'

  description: |
    It is primarily designed to benchmark a single project over its lifetime
    using a given suite of benchmarks. The results are displayed in an
    interactive web frontend that requires only a basic static webserver to
    host.
  doc_url: http://asv.readthedocs.io/en/latest/index.html
  dev_url: https://github.com/spacetelescope/asv

extra:
  recipe-maintainers:
    - CJ-Wright
