{% set name = "asv" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9afce3008094209b7e87b7b880bc6b8f2da303fdc6dd665c7be9f1057ecd5753

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools >=61.2
    - setuptools_scm >=6.2
    - wheel
  run:
    - python
    - asv_runner
    - json5
    - tabulate
    - colorama  # [win]
    - pyyaml  # [platform_python_implementation != "PyPy"]
    - pympler  # [platform_python_implementation != "PyPy"]

test:
  imports:
    - asv
#  requires:
#    - pytest
#  files:
#    - {{ SRC_DIR }}/test/
#  commands:
#    - cd {{ SRC_DIR }}/test/
#    - py.test

about:
  home: https://github.com/airspeed-velocity/asv
  license: BSD-3-Clause
  license_file: LICENSE.rst
  summary: A simple Python benchmarking tool with web-based reporting

  description: |
    It is primarily designed to benchmark a single project over its lifetime
    using a given suite of benchmarks. The results are displayed in an
    interactive web frontend that requires only a basic static webserver to
    host.
  doc_url: http://asv.readthedocs.io/en/latest/index.html
  dev_url: https://github.com/airspeed-velocity/asv

extra:
  recipe-maintainers:
    - CJ-Wright
    - saraedum
    - xhochy
    - mlondschien
    - mattip
    - jbrockmendel
    - datapythonista
    - HaoZeke
