{% set name = "asv" %}
{% set version = "0.6.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1d124184171cfe106e3e57ac04e3221b8d4571c9bd6ca2c6498a8c7407339df1
  patches:
    # https://github.com/airspeed-velocity/asv/pull/1407
    # https://github.com/airspeed-velocity/asv/issues/1406
    # https://github.com/conda-forge/asv-feedstock/issues/42
    - 1407-do-no-install-extra-dis.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools >=61.2
    - setuptools_scm >=6.2
    - wheel
  run:
    - python
    - asv_runner >=0.2.1
    - json5
    - tabulate
    - virtualenv
    - tomli
    - colorama  # [win]
    - pyyaml    # [python_impl != "pypy"]
    - pympler   # [python_impl != "pypy"]

test:
  imports:
    - asv
#  requires:
#    - pytest
#  files:
#    - {{ SRC_DIR }}/test/
#  commands:
#    - cd {{ SRC_DIR }}/test/
#    - py.test

about:
  home: https://github.com/airspeed-velocity/asv
  license: BSD-3-Clause
  license_file: LICENSE.rst
  summary: A simple Python benchmarking tool with web-based reporting

  description: |
    It is primarily designed to benchmark a single project over its lifetime
    using a given suite of benchmarks. The results are displayed in an
    interactive web frontend that requires only a basic static webserver to
    host.
  doc_url: http://asv.readthedocs.io/en/latest/index.html
  dev_url: https://github.com/airspeed-velocity/asv

extra:
  recipe-maintainers:
    - CJ-Wright
    - saraedum
    - xhochy
    - mlondschien
    - mattip
    - jbrockmendel
    - datapythonista
    - HaoZeke
