travis:
  secure:
    BINSTAR_TOKEN: bFgONlTUV/jtFkxytkE4HE8CKDhGRjg9iX75qR35sS773e3Fh9lZ053g5cT6uabjZCctQR/5Qq9DgjC0N/rQBAZsfbvKcrvybCSD4lAdwaKEAk8vmjaYBZ4nEbqb8mFcpSj9E7RO/aDCkQYngTocYyAAob0h4viOjl2FmEta1M7MNIJWxjJK0aT4878nRqpmomuXfi3XTRZFD4gKqxHHpoDocdzMhFNXN2L8GdFAPSjB3pCAKOiW0TBWdTPhpl2NTp3kOYyRLbKvYqRBAbgoAfrbpFbnRzs46obygJkf4nj7BDV+tMe+l2k7AwDR7S10sheC2xaEcV87o/9ovbgRA9lyjLI+D8M82PK+smMETaIbhWChCEtN+DXX/65k+zrvBfNBU21Jbhaa3gEM7HmonJftbDGHhNWupnLyMZJxw5UpeGcE98MzdY0BJX7Lz0wB+9lgy177Yw9n9P3OoyNooJsdlMiZBiROX3K4b0QeLsrhQObRoUQnxI+QCCTNT3dsNm5k2dPU++hnRrUqGm8Uu3eRMyYe59iCyJbuqGD1QYG37J+wCxDQMWGUT5d6FxfMzmlP0MIqg/AMBehMohZI4QIGSObOFqy97RKCd5BFe8XXwgaRvj/xjoUGEqajUFW9VX0c0rZIvdaMoE+ymoh+CpwIXbqNyNSRbO2gb6tbdT8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
